config/routes.rb
Rails.application.routes.draw do
  #resources :authentications
  resources :experiences
  resources :personal_infos
  resources :site_infos
  root 'home#index'
  get '/settings', to: "home#admin"
  get '*unmatched_route', to: 'application#not_found'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/personal_info.rb
class PersonalInfo < ApplicationRecord
end

app/controllers/personal_infos_controller.rb
class PersonalInfosController < ApplicationController
  before_action :set_personal_info, only: [:show, :edit, :update, :destroy]

  # GET /personal_infos
  # GET /personal_infos.json
  def index
    @personal_infos = PersonalInfo.all
  end

  # GET /personal_infos/1
  # GET /personal_infos/1.json
  def show
  end

  # GET /personal_infos/new
  def new
    @personal_info = PersonalInfo.new
  end

  # GET /personal_infos/1/edit
  def edit
  end

  # POST /personal_infos
  # POST /personal_infos.json
  def create
    @personal_info = PersonalInfo.new(personal_info_params)

    respond_to do |format|
      if @personal_info.save
        format.html { redirect_to @personal_info, notice: 'Personal info was successfully created.' }
        format.json { render :show, status: :created, location: @personal_info }
      else
        format.html { render :new }
        format.json { render json: @personal_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personal_infos/1
  # PATCH/PUT /personal_infos/1.json
  def update
    respond_to do |format|
      if @personal_info.update(personal_info_params)
        format.html { redirect_to @personal_info, notice: 'Personal info was successfully updated.' }
        format.json { render :show, status: :ok, location: @personal_info }
      else
        format.html { render :edit }
        format.json { render json: @personal_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_infos/1
  # DELETE /personal_infos/1.json
  def destroy
    @personal_info.destroy
    respond_to do |format|
      format.html { redirect_to personal_infos_url, notice: 'Personal info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal_info
      @personal_info = PersonalInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personal_info_params
      params.require(:personal_info).permit(:title, :value)
    end
end

app/helpers/personal_infos_helper.rb
module PersonalInfosHelper
end

app/views/personal_infos/_form.html.erb
<%= form_for(personal_info, :html => {:class => 'form-inline'}) do |f| %>
  <% if personal_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(personal_info.errors.count, "error") %> prohibited this personal_info from being saved:</h2>

      <ul>
      <% personal_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :value %>
    <%= f.text_field :value, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit :class => 'btn btn-success'%>
  </div>
<% end %>

app/views/personal_infos/edit.html.erb
<h1>Editing Personal Info</h1>

<%= render 'form', personal_info: @personal_info %>

<%= link_to  @personal_info, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-eye-open"></span>
      Show
<% end %>

<%= link_to  personal_infos_path, :class => 'btn btn-warning' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
      Back
<% end %>

app/views/personal_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personal Infos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personal_infos.each do |personal_info| %>
      <tr>
        <td><%= personal_info.title %></td>
        <td><%= personal_info.value %></td>
        <td>
          <%= link_to  personal_info, :class => 'btn btn-default' do %>
              <span class="glyphicon glyphicon-eye-open"></span>
              <div class="hidden-xs">
                Show
              </div>
          <% end %>
        </td>
        <td>
          <%= link_to edit_personal_info_path(personal_info), :class => 'btn btn-default' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              <div class="hidden-xs">
                Edit
              </div>
          <% end %>
        </td>
        <td>
          <%= link_to  personal_info, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' do %>
              <span class="glyphicon glyphicon-trash"></span>
              <div class="hidden-xs">
                Destroy
              </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to  new_personal_info_path, :class => 'btn btn-info' do %>
    <span class="glyphicon glyphicon-plus-sign"></span>
      New Personal Info
<% end %>

app/views/personal_infos/new.html.erb
<h1>New Personal Info</h1>

<%= render 'form', personal_info: @personal_info %>

<%= link_to  personal_infos_path, :class => 'btn btn-warning' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
      Back
<% end %>

app/views/personal_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @personal_info.title %>
</p>

<p>
  <strong>Value:</strong>
  <%= @personal_info.value %>
</p>

<%= link_to edit_personal_info_path(@personal_info), :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-pencil"></span>
      Edit
<% end %>

<%= link_to  personal_infos_path, :class => 'btn btn-warning' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
      Back
<% end %>