config/routes.rb
Rails.application.routes.draw do
  #resources :authentications
  resources :experiences
  resources :personal_infos
  resources :site_infos
  root 'home#index'
  get '/settings', to: "home#admin"
  get '*unmatched_route', to: 'application#not_found'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/site_info.rb
class SiteInfo < ApplicationRecord
end

app/controllers/site_infos_controller.rb
class SiteInfosController < ApplicationController
  before_action :set_site_info, only: [:show, :edit, :update, :destroy]

  # GET /site_infos
  # GET /site_infos.json
  def index
    @site_infos = SiteInfo.all
  end

  # GET /site_infos/1
  # GET /site_infos/1.json
  def show
  end

  # GET /site_infos/new
  def new
    @site_info = SiteInfo.new
  end

  # GET /site_infos/1/edit
  def edit
  end

  # POST /site_infos
  # POST /site_infos.json
  def create
    @site_info = SiteInfo.new(site_info_params)

    respond_to do |format|
      if @site_info.save
        format.html { redirect_to @site_info, notice: 'Site info was successfully created.' }
        format.json { render :show, status: :created, location: @site_info }
      else
        format.html { render :new }
        format.json { render json: @site_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /site_infos/1
  # PATCH/PUT /site_infos/1.json
  def update
    respond_to do |format|
      if @site_info.update(site_info_params)
        format.html { redirect_to @site_info, notice: 'Site info was successfully updated.' }
        format.json { render :show, status: :ok, location: @site_info }
      else
        format.html { render :edit }
        format.json { render json: @site_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_infos/1
  # DELETE /site_infos/1.json
  def destroy
    @site_info.destroy
    respond_to do |format|
      format.html { redirect_to site_infos_url, notice: 'Site info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site_info
      @site_info = SiteInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_info_params
      params.require(:site_info).permit(:name, :value)
    end
end

app/helpers/site_infos_helper.rb
module SiteInfosHelper
end

app/views/site_infos/_form.html.erb
<%= form_for(site_info, :html => {:class => 'form-inline'}) do |f| %>
  <% if site_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site_info.errors.count, "error") %> prohibited this site_info from being saved:</h2>

      <ul>
      <% site_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :value %>
    <%= f.text_field :value, :class => 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.submit :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/site_infos/edit.html.erb
<h1>Editing Site Info</h1>

<%= render 'form', site_info: @site_info %>


<%= link_to @site_info, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-eye-open"></span>
      Show
<% end %>

<%= link_to site_infos_path, :class => 'btn btn-warning' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
      Back
<% end %>

app/views/site_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Site Infos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @site_infos.each do |site_info| %>
      <tr>
        <td><%= site_info.name %></td>
        <td><%= site_info.value %></td>
        <td>
          <%= link_to  site_info , :class => 'btn btn-default' do %>
              <span class="glyphicon glyphicon-eye-open"></span>
              <div class="hidden-xs">
                Show
              </div>
          <% end %>
        </td>
        <td>
          <%= link_to edit_site_info_path(site_info),:class => 'btn btn-default' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              <div class="hidden-xs">
                Edit
              </div>
          <% end %>
        </td>
        <td>
          <%= link_to site_info, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' do %>
              <span class="glyphicon glyphicon-trash"></span>
              <div class="hidden-xs">
                Destroy
              </div>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_site_info_path,  :class => 'btn btn-info' do %>
    <span class="glyphicon glyphicon-plus-sign"></span>
      New Site Info
<% end %>

app/views/site_infos/new.html.erb
<h1>New Site Info</h1>

<%= render 'form', site_info: @site_info %>

<%= link_to site_infos_path, :class => 'btn btn-warning' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
      Back
<% end %>

app/views/site_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @site_info.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @site_info.value %>
</p>

<%= link_to edit_site_info_path(@site_info) , :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
<% end %>

<%= link_to site_infos_path , :class => 'btn btn-warning' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
    Back
<% end %>