config/routes.rb
Rails.application.routes.draw do
  #resources :authentications
  resources :experiences
  resources :personal_infos
  resources :site_infos
  root 'home#index'
  get '/settings', to: "home#admin"
  get '*unmatched_route', to: 'application#not_found'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/experience.rb
class Experience < ApplicationRecord
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :edit, :update, :destroy]

  # GET /experiences
  # GET /experiences.json
  def index
    @experiences = Experience.all
  end

  # GET /experiences/1
  # GET /experiences/1.json
  def show
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences
  # POST /experiences.json
  def create
    @experience = Experience.new(experience_params)

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: 'Experience was successfully created.' }
        format.json { render :show, status: :created, location: @experience }
      else
        format.html { render :new }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiences/1
  # PATCH/PUT /experiences/1.json
  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to @experience, notice: 'Experience was successfully updated.' }
        format.json { render :show, status: :ok, location: @experience }
      else
        format.html { render :edit }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1
  # DELETE /experiences/1.json
  def destroy
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url, notice: 'Experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experience_params
      params.require(:experience).permit(:title, :description, :start, :ending)
    end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_form.html.erb
<%= form_for(experience) do |f| %>
  <% if experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
      <% experience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, :class => 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :start %>
    <%= f.text_field :start, :class => 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :ending %>
    <%= f.text_field :ending, :class => 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.submit :class => 'btn btn-success'%>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<h1>Editing Experience</h1>

<%= render 'form', experience: @experience %>

<%= link_to @experience, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-eye-open"></span>
    Show
<% end %>

<%= link_to experiences_path , :class => 'btn btn-warning' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
    Back
<% end %>

app/views/experiences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Experiences</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Start</th>
      <th>Ending</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experiences.each do |experience| %>
      <tr>
        <td><%= experience.title %></td>
        <td><%= experience.description %></td>
        <td><%= experience.start %></td>
        <td><%= experience.ending %></td>
        <td>
          <%= link_to experience, :class => 'btn btn-default'  do %>
              <span class="glyphicon glyphicon-eye-open"></span>
              <div class="hidden-xs">
                Show
              </div>
          <% end %>
          </td>
        <td>
          <%= link_to edit_experience_path(experience), :class => 'btn btn-default' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              <div class="hidden-xs">
                Edit
              </div>
          <% end %>
        </td>
        <td>
          <%= link_to experience, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' do %>
              <span class="glyphicon glyphicon-trash"></span>
              <div class="hidden-xs">
                Destroy
              </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_experience_path, :class => 'btn btn-info' do %>
    <span class="glyphicon glyphicon-plus-sign"></span>
    New Experience
<% end %>

app/views/experiences/new.html.erb
<h1>New Experience</h1>

<%= render 'form', experience: @experience %>

<%= link_to experiences_path, :class => 'btn btn-warning' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
    Back
<% end %>

app/views/experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @experience.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @experience.description %>
</p>

<p>
  <strong>Start:</strong>
  <%= @experience.start %>
</p>

<p>
  <strong>Ending:</strong>
  <%= @experience.ending %>
</p>

<%= link_to edit_experience_path(@experience), :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
<% end %>

<%= link_to experiences_path, :class => 'btn btn-warning' do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
    Back
<% end %>